### ISSUE TITLE
Convert ESS Python course to e-learning course

### ISSUE THREAD

**Issue by thomasholmrod** [pan-training/python-course-ikon#1]
This task serves as test of Jupyter integration

- [x] clone python-course-ikon repository to this organization
- [x] create course(s) / modules in moodle and make the notebooks available from there
- [x] Create quiz for one notebook to demo how jupyter can work with moodle
- [ ] create quiz after each notebook
- [x] Get 2 - 3 persons to review course(s)

**Comment by thomasholmrod** [comment]
We can use this course for ESS IKON21

**Comment by moving-northwards** [comment]
There is a first quiz for the first chapter of notebooks ready for review.

**Comment by moving-northwards** [comment]
A quiz was made for the first set of notebooks and is in use. It was reviewed by Mads. 
A second smaller quiz was made for the second set of notebooks but was never released to students. 
It can be found under the old Python workshop page (IKON20)
